[tool.black]
line-length = 100
target_version = ['py34'] # required for backwards compatability with py27 and trailing commas
include = '\.pyi?$'
exclude = '''

(
  /(
    \.cache
    \.git
    \.sentinelsat.egg-info
    _build
    docs
  )/
)
'''